- alias: "Bedroom main light brightness set" 
  trigger:
    platform: state
    entity_id: input_number.bedroom_main_brightness
  action:
    - service: modbus.write_register
      data_template:
        hub: modbus
        unit: 10
        address: 0
        value: "{{ (states('input_number.bedroom_main_brightness'))|int }}"
- alias: "Bedroom main light brightness get"
  trigger:
    platform: state
    entity_id: sensor.bedroom_main_brightness
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.bedroom_main_brightness
        value: "{{ (states('sensor.bedroom_main_brightness'))|int }}"
- alias: "Bedroom led light brightness set" 
  trigger:
    platform: state
    entity_id: input_number.bedroom_led_brightness
  action:
    - service: modbus.write_register
      data_template:
        hub: modbus
        unit: 10
        address: 1
        value: "{{ (states('input_number.bedroom_led_brightness'))|int }}"
- alias: "Bedroom led light brightness get"
  trigger:
    platform: state
    entity_id: sensor.bedroom_led_brightness
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.bedroom_led_brightness
        value: "{{ (states('sensor.bedroom_led_brightness'))|int }}"
        
- alias: "Playroom main light brightness set" 
  trigger:
    platform: state
    entity_id: input_number.playroom_main_brightness
  action:
    - service: modbus.write_register
      data_template:
        hub: modbus
        unit: 11
        address: 0
        value: "{{ (states('input_number.playroom_main_brightness'))|int }}"
- alias: "Playroom main light brightness get"
  trigger:
    platform: state
    entity_id: sensor.playroom_main_brightness
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.playroom_main_brightness
        value: "{{ (states('sensor.playroom_main_brightness'))|int }}"
- alias: "Playroom led light brightness set" 
  trigger:
    platform: state
    entity_id: input_number.playroom_led_brightness
  action:
    - service: modbus.write_register
      data_template:
        hub: modbus
        unit: 11
        address: 1
        value: "{{ (states('input_number.playroom_led_brightness'))|int }}"
- alias: "Playroom led light brightness get"
  trigger:
    platform: state
    entity_id: sensor.playroom_led_brightness
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.playroom_led_brightness
        value: "{{ (states('sensor.playroom_led_brightness'))|int }}"
        
- alias: "Kitchen main light brightness set" 
  trigger:
    platform: state
    entity_id: input_number.kitchen_main_brightness
  action:
    - service: modbus.write_register
      data_template:
        hub: modbus
        unit: 12
        address: 0
        value: "{{ (states('input_number.kitchen_main_brightness'))|int }}"
- alias: "Kitchen main light brightness get"
  trigger:
    platform: state
    entity_id: sensor.kitchen_main_brightness
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.kitchen_main_brightness
        value: "{{ (states('sensor.kitchen_main_brightness'))|int }}"
- alias: "Kitchen led light brightness set" 
  trigger:
    platform: state
    entity_id: input_number.kitchen_led_brightness
  action:
    - service: modbus.write_register
      data_template:
        hub: modbus
        unit: 12
        address: 1
        value: "{{ (states('input_number.kitchen_led_brightness'))|int }}"
- alias: "Kitchen led light brightness get"
  trigger:
    platform: state
    entity_id: sensor.kitchen_led_brightness
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.kitchen_led_brightness
        value: "{{ (states('sensor.kitchen_led_brightness'))|int }}"
        
- alias: "Balcony thermostat temperature set" 
  trigger:
    platform: state
    entity_id: input_number.balcony_thermostat_temp
  action:
    - service: modbus.write_register
      data_template:
        hub: modbus
        unit: 31
        address: 1
        value: "{{ (states('input_number.balcony_thermostat_temp'))|int }}"
- alias: "Balcony thermostat temperature get"
  trigger:
    platform: state
    entity_id: sensor.balcony_thermostat_temp
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.balcony_thermostat_temp
        value: "{{ (states('sensor.balcony_thermostat_temp'))|int }}"
        
- alias: "Bathroom thermostat temperature set" 
  trigger:
    platform: state
    entity_id: input_number.bathroom_thermostat_temp
  action:
    - service: modbus.write_register
      data_template:
        hub: modbus
        unit: 50
        address: 1
        value: "{{ (states('input_number.bathroom_thermostat_temp'))|int }}"
- alias: "Bathroom thermostat temperature get"
  trigger:
    platform: state
    entity_id: sensor.bathroom_thermostat_temp
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.bathroom_thermostat_temp
        value: "{{ (states('sensor.bathroom_thermostat_temp'))|int }}"