recorder:
  purge_keep_days: 2
  db_url: 'sqlite:///:memory:'
  
logger:
  default: fatal
 # logs:
 #   homeassistant.core: fatal
 #   homeassistant.components.modbus: debug
 #   pymodbus.client: debug
 #   pymodbus.client.sync: debug
 #   pymodbus.transaction: debug
 #   pymodbus.framer.rtu_framer: debug
 #   pymodbus.factory: debug
  
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
modbus: !include modbus.yaml
input_number: !include input_number.yaml
input_boolean: !include input_boolean.yaml
climate: !include climate.yaml

mqtt:
  discovery: true
  broker: 127.0.0.1
  will_message:
    topic: 'homeassistant/status'
    payload: 'offline'
