recorder:
  purge_keep_days: 2
  db_url: 'sqlite:///:memory:'
  
logger:
  default: fatal
  logs:
    homeassistant.core: fatal
    homeassistant.components.modbus: debug
    pymodbus.client: debug
    pymodbus.client.sync: debug
    pymodbus.transaction: debug
    pymodbus.framer.rtu_framer: debug
    pymodbus.factory: debug
  
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
modbus: !include modbus.yaml

mqtt:
  discovery: true
  broker: 127.0.0.1
  will_message:
    topic: 'homeassistant/status'
    payload: 'offline'
    
input_number:
  bedroom_main_brightness:
    name: Main light brightness
    min: 10
    max: 100
    step: 5
  bedroom_led_brightness:
    name: Led light brightness
    min: 10
    max: 100
    step: 5
    
  playroom_main_brightness:
    name: Main light brightness
    min: 11
    max: 100
    step: 5
  playroom_led_brightness:
    name: Led light brightness
    min: 11
    max: 100
    step: 5
    
  kitchen_main_brightness:
    name: Main light brightness
    min: 12
    max: 100
    step: 5
  kitchen_led_brightness:
    name: Led light brightness
    min: 12
    max: 100
    step: 5  