name: modbus
type: serial
baudrate: 9600
bytesize: 8
method: rtu
parity: N
port: /dev/ttyS3
stopbits: 1
timeout: 10
delay: 3

switches:
    - name: bedroom_main_switch
      slave: 10
      address: 0
      write_type: coil
      verify:
      scan_interval: 10
    - name: bedroom_led_switch
      slave: 10
      address: 1
      write_type: coil
      verify:
      scan_interval: 10
    - name: playroom_left_bra_switch
      slave: 42
      address: 0
      write_type: coil
      verify:
      scan_interval: 10
    - name: playroom_right_bra_switch
      slave: 43
      address: 0
      write_type: coil
      verify:
      scan_interval: 10
      
    - name: playroom_main_switch
      slave: 11
      address: 0
      write_type: coil
      verify:
      scan_interval: 10
    - name: playroom_led_switch
      slave: 11
      address: 1
      write_type: coil
      verify:
      scan_interval: 10
    - name: playroom_bra_switch
      slave: 41
      address: 0
      write_type: coil
      verify:
      scan_interval: 10

    - name: kitchen_main_switch
      slave: 12
      address: 0
      write_type: coil
      verify:
      scan_interval: 10
    - name: kitchen_led_switch
      slave: 12
      address: 1
      write_type: coil
      verify:
      scan_interval: 10
      
    - name: balcony_main_switch
      slave: 31
      address: 0
      write_type: coil
      verify:
      scan_interval: 10
    - name: balcony_led_switch
      slave: 31
      address: 1
      write_type: coil
      verify:
      scan_interval: 10
    - name: balcony_thermostat
      slave: 31
      address: 0
      write_type: holding
      verify:
      scan_interval: 10
      
    - name: bathroom_heater_switch
      slave: 50
      address: 1
      write_type: coil
      verify:
      scan_interval: 10
    - name: bathroom_thermostat
      slave: 50
      address: 0
      write_type: holding
      verify:
      scan_interval: 10
    - name: bathroom_fan
      slave: 32
      address: 0
      write_type: coil
      verify:
      scan_interval: 10
    - name: bathroom_light
      slave: 32
      address: 2
      write_type: coil
      verify:
      scan_interval: 10
    - name: bathroom_fan_auto
      slave: 32
      address: 1
      write_type: holding
      verify:
      scan_interval: 300
      
    - name: toilet_fan
      slave: 32
      address: 1
      write_type: coil
      verify:
      scan_interval: 10
    - name: toilet_light
      slave: 32
      address: 3
      write_type: coil
      verify:
      scan_interval: 10
    - name: toilet_boiler
      slave: 32
      address: 4
      write_type: coil
      verify:
      scan_interval: 10
    - name: toilet_fan_auto
      slave: 32
      address: 3
      write_type: holding
      verify:
      scan_interval: 300
    - name: toilet_light_auto
      slave: 32
      address: 6
      write_type: holding
      verify:
      scan_interval: 300
      
    - name: heat_valve_1
      slave: 32
      address: 5
      write_type: coil
      verify:
      scan_interval: 600
    - name: heat_valve_2
      slave: 32
      address: 6
      write_type: coil
      verify:
      scan_interval: 600
    - name: heat_valve_3
      slave: 32
      address: 7
      write_type: coil
      verify:
      scan_interval: 600
      
    - name: hall_switch
      slave: 40
      address: 0
      write_type: coil
      verify:
      scan_interval: 10
      
binary_sensors:
    - name: balcony_thermostat_state
      slave: 31
      address: 2
      input_type: coil
      scan_interval: 30
    - name: bathroom_thermostat_state
      slave: 50
      address: 0
      input_type: coil
      scan_interval: 30
      
sensors:
    - name: bedroom_main_brightness
      slave: 10
      address: 0
      scan_interval: 10
    - name: bedroom_led_brightness
      slave: 10
      address: 1
      scan_interval: 10
    - name: bedroom_co2
      slave: 10
      address: 2
      unit_of_measurement: ppm
      scan_interval: 300
    - name: bedroom_temperature
      slave: 10
      address: 3
      unit_of_measurement: °C
      scale: 0.1
      offset: 0
      precision: 1
      scan_interval: 300
    - name: bedroom_humidity
      slave: 10
      address: 4
      unit_of_measurement: "%"
      scan_interval: 300
    - name: bedroom_light_level
      slave: 10
      address: 5
      unit_of_measurement: lx
      scan_interval: 300
      
    - name: playroom_main_brightness
      slave: 11
      address: 0
      scan_interval: 10
    - name: playroom_led_brightness
      slave: 11
      address: 1
      scan_interval: 10
    - name: playroom_co2
      slave: 11
      address: 2
      unit_of_measurement: ppm
      scan_interval: 300
    - name: playroom_temperature
      slave: 11
      address: 3
      unit_of_measurement: °C
      scale: 0.1
      offset: 0
      precision: 1
      scan_interval: 300
    - name: playroom_humidity
      slave: 11
      address: 4
      unit_of_measurement: "%"
      scan_interval: 300
    - name: playroom_light_level
      slave: 11
      address: 5
      unit_of_measurement: lx
      scan_interval: 300
      
    - name: kitchen_main_brightness
      slave: 12
      address: 0
      scan_interval: 10
    - name: kitchen_led_brightness
      slave: 12
      address: 1
      scan_interval: 10
    - name: kitchen_co2
      slave: 12
      address: 2
      unit_of_measurement: ppm
      scan_interval: 300
    - name: kitchen_temperature
      slave: 12
      address: 3
      unit_of_measurement: °C
      scale: 0.1
      offset: 0
      precision: 1
      scan_interval: 300
    - name: kitchen_humidity
      slave: 12
      address: 4
      unit_of_measurement: "%"
      scan_interval: 300
    - name: kitchen_light_level
      slave: 12
      address: 5
      unit_of_measurement: lx
      scan_interval: 300
      
    - name: balcony_thermostat_temp
      slave: 31
      address: 1
      input_type: holding
      scan_interval: 10
    - name: balcony_floor_temp
      slave: 31
      address: 4
      input_type: holding
      unit_of_measurement: °C
      scale: 0.1
      offset: 0
      precision: 1
      scan_interval: 300
    - name: balcony_air_temp
      slave: 31
      address: 5
      input_type: holding
      unit_of_measurement: °C
      scale: 0.1
      offset: 0
      precision: 1
      scan_interval: 300
    - name: balcony_humidity
      slave: 31
      address: 6
      input_type: holding
      unit_of_measurement: "%"
      scan_interval: 300
      
    - name: bathroom_thermostat_temp
      slave: 50
      address: 1
      input_type: holding
      scan_interval: 10
    - name: bathroom_floor_temp
      slave: 50
      address: 4
      input_type: holding
      unit_of_measurement: °C
      scale: 0.1
      offset: 0
      precision: 1
      scan_interval: 300
    - name: bathroom_air_temp
      slave: 50
      address: 5
      input_type: holding
      unit_of_measurement: °C
      scale: 0.1
      offset: 0
      precision: 1
      scan_interval: 300
    - name: bathroom_temp
      slave: 32
      address: 2
      input_type: input
      unit_of_measurement: °C
      scale: 0.1
      offset: 0
      precision: 1
      scan_interval: 300
    - name: bathroom_humidity
      slave: 32
      address: 3
      input_type: input
      unit_of_measurement: "%"
      scan_interval: 300
    - name: bathroom_brightness
      slave: 32
      address: 0
      input_type: holding
      scan_interval: 10
      
    - name: toilet_presence
      slave: 32
      address: 0
      input_type: input
      scan_interval: 10
    - name: toilet_temp
      slave: 32
      address: 1
      input_type: input
      unit_of_measurement: °C
      scale: 0.1
      offset: 0
      precision: 1
      scan_interval: 300
    - name: toilet_brightness
      slave: 32
      address: 5
      input_type: holding
      scan_interval: 10
      
    - name: total_power_voltage
      unit_of_measurement: V
      slave: 1
      address: 0
      input_type: input
      scale: 0.1
      offset: 0
      precision: 2
      scan_interval: 300
    - name: total_power_current
      unit_of_measurement: A
      slave: 1
      address: 1
      count: 2
      swap: word
      input_type: input
      scale: 0.001
      offset: 0
      precision: 2
      scan_interval: 300
    - name: total_power_power
      unit_of_measurement: W
      slave: 1
      address: 3
      count: 2
      swap: word
      input_type: input
      scale: 0.1
      offset: 0
      precision: 1
      scan_interval: 300
    - name: total_power_wh
      unit_of_measurement: Wh
      slave: 1
      address: 5
      count: 2
      swap: word
      input_type: input
      scale: 1
      offset: 0
      precision: 1
      scan_interval: 300
    - name: total_power_frequency
      unit_of_measurement: Hz
      slave: 1
      address: 7
      input_type: input
      scale: 0.1
      offset: 0
      precision: 1
      scan_interval: 300
    - name: total_power_pf
      slave: 1
      address: 8
      input_type: input
      scale: 0.01
      offset: 0
      precision: 1
      scan_interval: 300
    - name: power_frequency
      unit_of_measurement: Hz
      slave: 3
      address: 0
      input_type: input
      scale: 0.01
      offset: 0
      precision: 2
      scan_interval: 300 
    - name: power_voltage
      unit_of_measurement: V
      slave: 3
      address: 1
      input_type: input
      scale: 0.01
      offset: 0
      precision: 2
      scan_interval: 300
    - name: power_current1
      unit_of_measurement: A
      slave: 3
      address: 5
      swap: word
      input_type: input
      scale: 0.01
      offset: 0
      precision: 2
      scan_interval: 300
    - name: power_current2
      unit_of_measurement: A
      slave: 3
      address: 6
      swap: word
      input_type: input
      scale: 0.01
      offset: 0
      precision: 2
      scan_interval: 300
    - name: power_current3
      unit_of_measurement: A
      slave: 3
      address: 7
      swap: word
      input_type: input
      scale: 0.01
      offset: 0
      precision: 2
      scan_interval: 300
    - name: power_current4
      unit_of_measurement: A
      slave: 3
      address: 8
      swap: word
      input_type: input
      scale: 0.01
      offset: 0
      precision: 2
      scan_interval: 300
    - name: power_current5
      unit_of_measurement: A
      slave: 3
      address: 9
      swap: word
      input_type: input
      scale: 0.01
      offset: 0
      precision: 2
      scan_interval: 300
    - name: power_current6
      unit_of_measurement: A
      slave: 3
      address: 10
      swap: word
      input_type: input
      scale: 0.01
      offset: 0
      precision: 2
      scan_interval: 300
    - name: power_current7
      unit_of_measurement: A
      slave: 3
      address: 11
      swap: word
      input_type: input
      scale: 0.01
      offset: 0
      precision: 2
      scan_interval: 300
    - name: power_current8
      unit_of_measurement: A
      slave: 3
      address: 12
      swap: word
      input_type: input
      scale: 0.01
      offset: 0
      precision: 2
      scan_interval: 300
    - name: power_current9
      unit_of_measurement: A
      slave: 3
      address: 13
      swap: word
      input_type: input
      scale: 0.01
      offset: 0
      precision: 2
      scan_interval: 300
    - name: power_pf1
      slave: 3
      address: 14
      input_type: input
      scale: 0.01
      offset: 0
      precision: 1
      scan_interval: 300
    - name: power_pf2
      slave: 3
      address: 15
      input_type: input
      scale: 0.01
      offset: 0
      precision: 1
      scan_interval: 300
    - name: power_pf3
      slave: 3
      address: 16
      input_type: input
      scale: 0.01
      offset: 0
      precision: 1
      scan_interval: 300
    - name: power_pf4
      slave: 3
      address: 17
      input_type: input
      scale: 0.01
      offset: 0
      precision: 1
      scan_interval: 300
    - name: power_pf5
      slave: 3
      address: 18
      input_type: input
      scale: 0.01
      offset: 0
      precision: 1
      scan_interval: 300
    - name: power_pf6
      slave: 3
      address: 19
      input_type: input
      scale: 0.01
      offset: 0
      precision: 1
      scan_interval: 300
    - name: power_pf7
      slave: 3
      address: 20
      input_type: input
      scale: 0.01
      offset: 0
      precision: 1
      scan_interval: 300
    - name: power_pf8
      slave: 3
      address: 21
      input_type: input
      scale: 0.01
      offset: 0
      precision: 1
      scan_interval: 300
    - name: power_pf9
      slave: 3
      address: 22
      input_type: input
      scale: 0.01
      offset: 0
      precision: 1
      scan_interval: 300