- platform: mqtt
  name: 'Kitchen temperature Zigbee'
  state_topic: 'zigbee2mqtt/kitchen_temp_humidity'
  unit_of_measurement: '°C'
  value_template: "{{ value_json.temperature | round(1) }}"
  availability_topic: "zigbee2mqtt/bridge/state"
  device_class: "temperature"
- platform: mqtt
  name: 'Kitchen humidity Zigbee'
  state_topic: 'zigbee2mqtt/kitchen_temp_humidity'
  unit_of_measurement: '%'
  value_template: "{{ value_json.humidity | round(0) }}"
  availability_topic: "zigbee2mqtt/bridge/state"
  device_class: "humidity"
