
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
input_number: !include input_number.yaml
modbus: !include modbus.yaml

recorder:
  purge_keep_days: 7
  db_url: 'sqlite:///:memory:'